# Generated by Django 4.1.4 on 2022-12-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userFirstName', models.CharField(max_length=200)),
                ('userLastName', models.CharField(max_length=200)),
                ('userPasswort', models.CharField(max_length=200)),
            ],
        ),
    ]
