# Generated by Django 4.1.4 on 2022-12-20 09:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myWEBSHOP', '0002_mtb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bikeType', models.CharField(max_length=200)),
                ('bikeDescription', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producerName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rentalprocesses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentalprocessStartDate', models.DateField(default=datetime.date.today)),
                ('rentalprocessEndDate', models.DateField()),
                ('rentalprocessUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myWEBSHOP.users')),
            ],
        ),
        migrations.DeleteModel(
            name='MTB',
        ),
    ]
